# Workflow to compile and deploy a Next.js website to a custom hosting service via FTP
#
name: Build and Deploy Next.js to sweb via FTP

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: true
          package_json_file: package.json

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'pnpm'

      - name: Install required packages with pnpm
        run: pnpm install

      - name: Compile using Next.js
        run: pnpm next build

      - name: Convert to Static HTML using Next.js
        run: pnpm next export

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Custom Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/y/yarikbahon/jawhealth/public_html
          local-dir: ./out
