# Workflow to compile and deploy a Next.js website to a custom hosting service via FTP
#
name: Build and Deploy Next.js to sweb via FTP

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Code
        uses: actions/checkout@v3
        
      - name: Identify package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "command=install" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "command=ci" >> $GITHUB_ENV
            echo "runner=npx --no-install" >> $GITHUB_ENV
          else
            echo "Package manager not identified"
            exit 1
          fi

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: ${{ env.manager }}

      - name: Install required packages
        run: ${{ env.manager }} ${{ env.command }}

      - name: Compile using Next.js
        run: ${{ env.runner }} next build

      - name: Convert to Static HTML using Next.js
        run: ${{ env.runner }} next export

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Custom Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/y/yarikbahon/jawhealth/public_html
          local-dir: ./out
